version: "3"
services:
  app:
    image: pudding/docker-app:docker-app-Temporal-File-Arrangement-20250224.104348
    tty: true
    command: node /app/index.js "/input/__INPUT__"
    environment:
      - CONTAINER_NAME=docker-app-temporal-file-arragnement-app
      - LOCAL_VOLUMN_PATH=/input/
      - RUN_COMMAND=node /app/index.js
    volumes: 
      - ./app:/app/
      - __SOURCE__:/input/
      - __SOURCE__:/output/